### PR TITLE
Comment out message sent to STDERR.

### PR DESCRIPTION
**Pull request by aeden**
Introduced in 55b71959e8a3b072bd6de19bd0674cfb9e26a832

### CODE REVIEW

**Comment by cjheath** [comment]
This message is from the compiler (though that might get run by Polyglot at load time).
It indicates (although not reliably, unfortunately) a problem with the grammar being processed.
Why should that warning be commented out?
What alternative notification method should be used?
Can you correct the warning so that it only occurs when there actually is a problem (I have found it difficult to find a correct fix)?

**Comment by aeden** [comment]
The warning occurs when this file is parsed: https://github.com/craigw/dns-zonefile/blob/master/lib/dns/zonefile.treetop

I honestly don't understand the internals of the treetop well enough to understand why the warning exists, although it looks like it was introduced recently as part of an in-progress change.

The reasons I commented it out are:

1. The parsed file still appears to perform as expected (although perhaps in certain cases it will not work as expected, I'm not 100% sure)
2. The file I referenced above is parsed once at runtime when https://github.com/craigw/dns-zonefile/blob/master/lib/dns/zonefile.rb is loaded, and thus this warning appears when running tests in systems that depend on the dns-zonefile library, when starting an interactive session with irb when the dns-zonefile library is loaded etc.
3. It's unclear from the warning what should be done, if anything.

I'm not sure if an alternative warning is possible, but perhaps if the warning made it clear how I can fix the problem, then I can fix the problem in the zonefile grammar.

**Comment by cjheath** [comment]
The message should not appear when loading the generated .rb file. If the .treetop file is being loaded (because no generated .rb file was found) then the compiler will be run and the message may appear. So a work-around for you is to ensure that the "tt" command line has been used to produce the .rb file.

I will need to try the grammar you linked to in order to see why the message is appearing, but I'm travelling at present so it might be a few days.

**Comment by aeden** [comment]
> The message should not appear when loading the generated .rb file.

This is true, but the library doesn't generate a .rb version, it always loads it on demand. This approach allows the grammar to be extended by dependent projects (which is beneficial in the case of a zone file parser).

**Comment by cjheath** [comment]
There will be a simple change to the treetop file that avoids the warning. I will find it and let you know, since I cannot guarantee a fix to  the underlying problem as quickly.

**Comment by aeden** [comment]
Thanks! I await your proposed change to the treetop file.

**Comment by cjheath** [comment]
I made the required changes, but they are too unpleasant. I've not been able to discover why this message comes up unexpectedly in Ruby 2.2 (cause by a change of language semantics!), so I guess I will have to disable it. Give me another day to investigate, today was full with other things.

**Comment by cjheath** [comment]
This problem (caused by incorrect detection of the warning condition) has been fixed properly and released as Treetop 1.6.6. Please install and test it. The warning to $STDERR should only now occur when there is a genuine problem with ignored inline modules, see e.g. the last test in spec/compiler/parenthesized_expression_spec.rb

**Comment by aeden** [comment]
Excellent, thanks for tracking it down!

**Pull request closed without merging**
